name: CI
on: [workflow_dispatch]
env:
  CI: true

jobs:
  functional-tests:
    name: Functional
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install deps
        run: npm install
        run: npx playwright install-deps
      - name: Run functional tests
        run: npm run build
        run: npm -w packages/dom run test:functional
